### ISSUE TITLE
Output of mycode is not formatted

### ISSUE THREAD

**Issue by daliahabiby** [daliahabiby/mytest#1]
The addition of the code x+y has produced output that is unlabeled. The user will not easily be able to tell the output values apart especially with long vectors. @ryantmoore see if you can add some sort of clear print method using a function.

**Comment by ryantmoore** [comment]
Can you assign me to this issue? Also, consider linting your code.

**Comment by ryantmoore** [comment]
Thanks for this assignment. I've linted the code in 9fb403e8f5b2ade47b5da097c596523f287ce792, but probably will not write a print method, since there is no class here. Please re-open or create a new issue if there's more to do!
